#!/bin/sh -e

RED='\033[1;31m'
GREEN='\033[1;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

HOST=""
OTHER_ARGS=""

while [ $# -gt 0 ]; do
  case "$1" in
    --host=*)
      HOSt="${1#*=}"
      shift
      ;;
    --host)
      HOST="$2"
      shift 2
      ;;
    *)
      OTHER_ARGS="$OTHER_ARGS $1"
      shift
      ;;
  esac
done

if [ -n "$HOST" ]; then
  echo "${YELLOW}Building for named host: $HOST${NC}"
  SYSTEM=$(uname -m)

  case "$SYSTEM" in
    x86_64)
      FLAKE_TARGET="${HOST}@x86_64-darwin"
      ;;
    arm64)
      FLAKE_TARGET="${HOST}@aarch64-darwin"
      ;;
    *)
      echo "${RED}Unsupported architecture: $SYSTEM${NC}"
      exit 1
      ;;
  esac
else
  SYSTEM=$(uname -m)

  case "$SYSTEM" in
    x86_64)
      FLAKE_TARGET="x86_64-darwin"
      ;;
    arm64)
      FLAKE_TARGET="aarch64-darwin"
      ;;
    *)
      echo "${RED}Unsupported architecture: $SYSTEM${NC}"
      exit 1
      ;;
  esac
  echo "${YELLOW}Building for platform: $FLAKE_TARGET${NC}"
fi

export NIXPKGS_ALLOW_UNFREE=1

echo "${YELLOW}Starting build...${NC}"
# echo "nix --extra-experimental-features 'nix-command flakes' build .#$FLAKE_TARGET $OTHER_ARGS"
nix --extra-experimental-features 'nix-command flakes' build .#darwinConfigurations.$FLAKE_TARGET.system $OTHER_ARGS

echo "${YELLOW}Switching to new generation...${NC}"
# echo "./result/sw/bin/darwin-rebuild switch --flake .#${FLAKE_TARGET} $OTHER_ARGS"
sudo ./result/sw/bin/darwin-rebuild switch --flake .#${FLAKE_TARGET} $OTHER_ARGS

echo "${YELLOW}Cleaning up...${NC}"
unlink ./result

echo "${GREEN}Switch to new generation complete!${NC}"
