#!/bin/sh -e

GREEN='\033[1;32m'
YELLOW='\033[1;33m'
RED='\033[1;31m'
NC='\033[0m'

if [[ $# -eq 0 ]]; then
	echo "A host is required to properly build and switch the flake"
	echo "Usage: nix run '.#build-switch' -- HOST_NAME"
	exit 1
fi

HOST=$1
SYSTEM_TYPE="aarch64-darwin"
FLAKE_SYSTEM="darwinConfigurations.${SYSTEM_TYPE}.${HOST}.system"

# Shift the args so any additional ones are sent to the script
shift 1

export NIXPKGS_ALLOW_UNFREE=1

echo "${YELLOW}Starting build...${NC}"
echo "nix --extra-experimental-features 'nix-command flakes' build .#$FLAKE_SYSTEM $@"
nix --extra-experimental-features 'nix-command flakes' build .#$FLAKE_SYSTEM $@

echo "${YELLOW}Switching to new generation...${NC}"
./result/sw/bin/darwin-rebuild switch --flake .#${SYSTEM_TYPE}.${HOST} $@

echo "${YELLOW}Cleaning up...${NC}"
unlink ./result

echo "${GREEN}Switch to new generation complete!${NC}"
