#!/bin/sh -e

RED='\033[1;31m'
GREEN='\033[1;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

USERNAME="${USER:-$(whoami)}"
ARCH=$(uname -m)
OS=$(uname -s)

case "${OS}:${ARCH}" in
  Darwin:arm64)
    SYSTEM="aarch64-darwin"
    ;;
  *)
    printf "${RED}Unsupported platform: %s/%s${NC}\n" "$OS" "$ARCH"
    exit 1
    ;;
esac

FLAKE_TARGET="${USERNAME}@${SYSTEM}"

printf "${YELLOW}Building Home Manager configuration: %s${NC}\n" "$FLAKE_TARGET"

nix --extra-experimental-features 'nix-command flakes' \
  build ".#homeConfigurations.\"${FLAKE_TARGET}\".activationPackage" "$@"

printf "${YELLOW}Activating Home Manager configuration...${NC}\n"
./result/activate

if [ -L ./result ]; then
  unlink ./result
fi

printf "${GREEN}Home Manager activation complete!${NC}\n"
