#!/bin/sh -e

RED='\033[1;31m'
GREEN='\033[1;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

echo "${YELLOW}Cleaning up old system generations...${NC}"

sudo nix-collect-garbage --delete-older-than 7d

echo "${GREEN}Cleanup complete!${NC}"
